language: node_js
node_js:
  - 10
cache: yarn
branches:
  except:
    - /^no-ci.*$/
script:
  - yarn jsdoc
  - yarn autocomplete
  - yarn format:ci
  - yarn tslint
  - yarn test
  - yarn test-coveralls
