import es from 'estree'

import { full } from '../../utils/walkers'

/**
 * Strips out location information from an AST.
 *
 * The local imports test suites only care about the structure of the
 * transformed AST. The line & column numbers, as well as the character
 * offsets of each node in the ASTs derived from parsing the pre-transform
 * code & the equivalent post-transform code will not be the same.
 * Note that it is insufficient to pass in 'locations: false' into the acorn
 * parser as there will still be 'start' & 'end' properties attached to nodes
 * which represent character offsets.
 *
 * WARNING: Since this function is only used for test suites, it mutates
 * the original AST for convenience instead of creating a copy.
 *
 * @param node The AST which should be stripped of location information.
 */
export const stripLocationInfo = (node: es.Node): es.Node => {
  // The 'start' & 'end' properties are not typed in ESTree, but they exist
  // on some nodes in the AST generated by acorn parser.
  full(node, (node: es.Node & { start?: number; end?: number }) => {
    // Line & column numbers
    delete node.loc
    // Character offsets
    delete node.start
    delete node.end
  })
  return node
}
